import { v4 } from "uuid";

export const CARDS = [
    {
        id: v4(),
        color: 'blue',
        src: '/public/images/icon-facebook.svg',
        alt: 'Imagen 1',
        text1: '@nathanf',
        text2: '1987',
        text3: 'FOLLOWERS',
        text4: '12 Today',
        arrow: '/public/images/icon-up.svg',
    },
    {
        id: v4(),
        color: 'blue',
        src: '/public/images/icon-twitter.svg',
        alt: 'Imagen 1',
        text1: '@nathanf',
        text2: '1044',
        text3: 'FOLLOWERS',
        text4: '99 Today',
        arrow: '/public/images/icon-up.svg',
    },
    {
        id: v4(),
        color: 'orange',
        src: '/public/images/icon-instagram.svg',
        alt: 'Imagen 1',
        text1: '@realnathanf',
        text2: '11k',
        text3: 'FOLLOWERS',
        text4: '1099 Today',
        arrow: '/public/images/icon-up.svg',
    },
    {
        id: v4(),
        color: 'red',
        src: '/public/images/icon-youtube.svg',
        alt: 'Imagen 1',
        text1: 'Nathan F.',
        text2: '8239',
        text3: 'FOLLOWERS',
        text4: '144 Today',
        arrow: '/public/images/icon-down.svg',
        colorLetra: 'red',
    },
]

