import { v4 } from "uuid";

export const LIKES = [
    {
        id: v4(),
        src: '/public/images/icon-facebook.svg',
        src2: '/public/images/icon-up.svg',
        alt: 'imagen 1',
        t1: 'Page Views',
        t2: '87',
        t3: '3%',
    },
    {
        id: v4(),
        src: '/public/images/icon-facebook.svg',
        src2: '/public/images/icon-down.svg',
        alt: 'imagen 2',
        t1: 'Likes',
        t2: '52',
        t3: '2%',
        color: 'red',
    },
    {
        id: v4(),
        src: '/public/images/icon-instagram.svg',
        src2: '/public/images/icon-up.svg',
        alt: 'imagen 3',
        t1: 'Likes',
        t2: '5462',
        t3: '2257%',
    },
    {
        id: v4(),
        src: '/public/images/icon-instagram.svg',
        src2: '/public/images/icon-up.svg',
        alt: 'imagen 4',
        t1: 'Profile Views',
        t2: '52k',
        t3: '1375%',
    },
    {
        id: v4(),
        src: '/public/images/icon-twitter.svg',
        src2: '/public/images/icon-up.svg',
        alt: 'imagen 5',
        t1: 'Retweets',
        t2: '117',
        t3: '303%',
    },
    {
        id: v4(),
        src: '/public/images/icon-twitter.svg',
        src2: '/public/images/icon-up.svg',
        alt: 'imagen 6',
        t1: 'Likes',
        t2: '507',
        t3: '553%',
    },
    {
        id: v4(),
        src: '/public/images/icon-youtube.svg',
        src2: '/public/images/icon-down.svg',
        alt: 'imagen 7',
        t1: 'Likes',
        t2: '107',
        t3: '10%',
        color: 'red',
    },
    {
        id: v4(),
        src: '/public/images/icon-youtube.svg',
        src2: '/public/images/icon-down.svg',
        alt: 'imagen 8',
        t1: 'Total Views',
        t2: '1407',
        t3: '12%',
        color: 'red',
    },
]